Source/CryptoAlert/Controllers/FavoriteCoinsController.cs
using CryptoAlert.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace CryptoAlert.WebApp.Controllers
{
    public class FavoriteCoinsController : Controller
    {
        private readonly FavoriteCoinsViewModel _favoriteCoinsViewModel = new FavoriteCoinsViewModel();

        public IActionResult Index()
        {
            ViewData.Add("Coins", _favoriteCoinsViewModel.ListOfAllFavoriteCoins);

            return View(_favoriteCoinsViewModel);
        }
    }
}

Source/CryptoAlert/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using CryptoAlertCore.Authentication.Factories;
using CryptoAlertCore.Authentication.Services;
using CryptoAlertCore.Authentication;
using Newtonsoft.Json;
using CryptoAlert.WebApp.Models;
using Microsoft.AspNetCore.Http;
using System;
using CryptoAlertCore.Models;

namespace CryptoAlert.WebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly LoginViewModel _loginViewModel = new LoginViewModel();

        public IActionResult Index()
        {
            return View(_loginViewModel);
        }

        [HttpPost]
        public IActionResult Index(string email, string pass)
        {
            IUserAuthenticationService userAuthenticationService = new UserAuthenticationServiceFactory().Create();
            var userLogin = new UserLogin
            {
                Email = email,
                Password = pass
            };

            var token = AuthenticateUser(userLogin, userAuthenticationService);
            if (token == null)
            {
                _loginViewModel.IncorrectPassword = true;
                return View(_loginViewModel);
            }

            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddHours(24)
            };
            Response.Cookies.Append("jwt", token.Content, cookieOptions);

            return RedirectToAction("Index", "Coins");
        }

        public IActionResult Logout()
        {
            Response.Cookies.Delete("jwt");
            return RedirectToAction("Index", "Coins");
        }

        private Token AuthenticateUser(UserLogin userLogin, IUserAuthenticationService userAuthenticationService)
        {
            return userAuthenticationService.AuthenticateUserFromJson(JsonConvert.SerializeObject(userLogin));
        }
    }
}

Source/CryptoAlert/Controllers/UserController.cs
using CryptoAlert.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace CryptoAlert.WebApp.Controllers
{
	public class UserController : Controller
	{
		private readonly UserViewModel _userViewModel = new UserViewModel();

		public IActionResult Index()
		{
			return View(_userViewModel);
		}
	}
}

Source/CryptoAlert/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CryptoAlert</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CryptoAlert</a>
			</div>
			<div class="navbar-collapse collapse justify-content-between">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Coins" asp-action="Index">Coins</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
					@{
						if (HttpContextAccessor.HttpContext.Request.Cookies.ContainsKey("jwt"))
						{
							<li><a asp-area="" asp-controller="FavoriteCoins" asp-action="Index">Show favorites</a></li>
						}
					}
				</ul>
				<ul class="nav navbar-nav navbar-right">
					@{
						if (HttpContextAccessor.HttpContext.Request.Cookies.ContainsKey("jwt"))
						{

							<li>
								<a asp-area="" asp-controller="User" asp-action="Index">Profile</a>
							</li>
							<li>
								<a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
							</li>
						}
						else
						{
							<li>
								<a asp-area="" asp-controller="Login" asp-action="Index">Login</a>
							</li>
						}
					}

				</ul>
			</div>
		</div>
	</nav>

	<partial name="_CookieConsentPartial" />

	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2018 - CryptoAlert</p>
		</footer>
	</div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>